:walkthrough: Demo

[id='demo']
= {walkthrough}

This solution pattern will walk you through the creation of a Kafka Stream, and will also have you create a topic and connect it to the stream.

This Solution Pattern consists of the following components:

* Red Hat OpenShift Streams for Apache Kafka (RHOSAK)
* RHOSAK CLI


[type=walkthroughResource,serviceName=rhosak]
.Red Hat OpenShift Streams for Apache Kafka (RHOSAK)
****
* link:https://cloud.redhat.com[Control plane, window="_blank"]
* link:https://cloud.redhat.com[Data plane, window="_blank"]
****

[type=walkthroughResource,serviceName=rhosak-cli]
.RHOSAK CLI
****
* link:https://cloud.redhat.com[Console, window="_blank"]
****


[time=5]

[id='creating-kafka']


:sectnums:


==  Creating a Kafka instance

For this task, you will create a Kafka instance by using the built-in quick start within the Kafka user interface.

. Open the [.app-launch-control]#Kafka control plane#.
. Follow the quick start steps within the app to create a kafka instance.
. Once the quick start is complete, you will return to this solution pattern to create a topic.

[type=verification]
verify-through-app

[time=5]
== Creating a topic

For this task, you will create a Kafka topic.

. Open the [.app-launch-data]#Kafka data plane#.
. Follow the quick start steps within the app to create a Kafka topic.
. Once the quick start is complete, you will return to this solution pattern to begin using that topic.

[type=verification]
verify-through-app


[time=5]
== Connecting to a topic

For this task, you will connect a topic to the kafka stream.

=== Update Quarkus Configuration File

Open your favourate editor and update the
link:src/main/resources/application.properties[application.properties]
with the following content

[source,properties]
----
kafka.bootstrap.servers=<kafka-bootstrap-server>:443
sasl.mechanism=PLAIN
security.protocol=SASL_SSL

sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="<USER>" \
  password="<PASSWORD>";
----

____
NOTE: `<kafka-bootstrap-server>` is the bootstrap server url
____

Save, now you are ready to start the application.

=== Start the application

Run the application in dev mode with.

[source,bash]
----
./mvnw quarkus:dev
----

Then, open your browser to `http://localhost:8080/prices.html`, and you
should see a fluctuating price.

=== Anatomy

In addition to the `prices.html` page, the application is composed by 3
components:

* `PriceGenerator` - a bean generating random price. They are sent to a
Kafka topic
* `PriceConverter` - on the consuming side, the `PriceConverter`
receives the Kafka message and convert the price. The result is sent to
an in-memory stream of data
* `PriceResource` - the `PriceResource` retrieves the in-memory stream
of data in which the converted prices are sent and send these prices to
the browser using Server-Sent Events.

The interaction with Kafka is managed by MicroProfile Reactive
Messaging. The configuration is located in the
link:src/main/resources/application.properties[application
configuration].

=== Running in JVM mode

Package the application with

[source,bash]
----
./mvnw clean package
----

and run with

[source,bash]
----
java -jar target/mas-kafka-1.0-SNAPSHOT-runner.jar
----

=== Running in native

You can compile the application into a native binary using:

[source,bash]
----
./mvnw clean install -Pnative
----

and run with:

[source,bash]
----
./target/mas-kafka-1.0-SNAPSHOT-runner
----

[type=verification]
Did you connect the topic to the kafka stream?

[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.
