schema: ./server/mockapi/schema.graphql

extensions:
  codegen:
    generates:
      ./client/Entities/Entities.generated.ts:
        plugins:
          - typescript
          - typescript-react-apollo
          - add:
              content: '/* eslint-disable */'
    config:
      skipTypeNameForRoot: true
      skipTypename: true
